#!/bin/sh
#
# ustripe startup routines:
# - clean up /var/run/ustripe
# - ensure that the udev event for hiddev* has been triggered
#

### BEGIN INIT INFO
# Provides:          ustripe-cleanup
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     S
# Default-Stop:
# Short-Description: ustripe cleanup
### END INIT INFO

set -e

if [ "$1" = "start" ] ; then
    if [ -d /var/run/ustripe ] ; then
        rm -rf /var/run/ustripe
    fi
    install -m 0755 -d /var/run/ustripe
fi

# HACK FIXME - This is done to make sure that ustriped is loaded at startup,
# but it shouldn't be necessary.
if [ "$1" = "start" ] ; then
    udevadm trigger --sysname-match='hiddev*'
fi

exit 0

# vim:set ts=4 sw=4 sts=4 expandtab:
