Document: ustripe
Title: Debian ustripe Manual
Author: <insert document author here>
Abstract: This manual describes what ustripe is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ustripe/ustripe.sgml.gz

Format: postscript
Files: /usr/share/doc/ustripe/ustripe.ps.gz

Format: text
Files: /usr/share/doc/ustripe/ustripe.text.gz

Format: HTML
Index: /usr/share/doc/ustripe/html/index.html
Files: /usr/share/doc/ustripe/html/*.html
